#!/usr/bin/env bash
# Pretabs-Kitty — Interactive setup wizard
# Generates a custom Kitty tab-launch script and optionally wires it into .zshrc

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── Colors ────────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
BOLD='\033[1m'
DIM='\033[2m'
RESET='\033[0m'

# ── Header ────────────────────────────────────────────────────────────────────
echo -e "${CYAN}${BOLD}"
echo "  ╔══════════════════════════════════════╗"
echo "  ║       Pretabs-Kitty  •  Setup        ║"
echo "  ╚══════════════════════════════════════╝"
echo -e "${RESET}"

# ── 1. Number of tabs ─────────────────────────────────────────────────────────
while true; do
    read -rp "$(echo -e "${YELLOW}How many tabs do you want? ${RESET}")" num_tabs
    [[ "$num_tabs" =~ ^[1-9][0-9]*$ ]] && break
    echo -e "${RED}  ✖ Please enter a positive integer.${RESET}"
done

# ── 2. Tab names ──────────────────────────────────────────────────────────────
declare -a tab_names
echo ""
echo -e "${CYAN}Name each tab:${RESET}"
for ((i = 1; i <= num_tabs; i++)); do
    while true; do
        read -rp "  $(echo -e "${DIM}Tab ${i}${RESET}") name: " tname
        [[ -n "$tname" ]] && break
        echo -e "${RED}  ✖ Tab name cannot be empty.${RESET}"
    done
    tab_names+=("$tname")
done

# ── 3. Focus tab ──────────────────────────────────────────────────────────────
echo ""
if (( num_tabs == 1 )); then
    focus_idx=0
else
    echo -e "${CYAN}Which tab should have focus after launch?${RESET}"
    for ((i = 1; i <= num_tabs; i++)); do
        echo -e "  ${DIM}${i})${RESET} ${tab_names[$((i-1))]}"
    done
    while true; do
        read -rp "$(echo -e "${YELLOW}Tab number [1-${num_tabs}]: ${RESET}")" focus_num
        if [[ "$focus_num" =~ ^[0-9]+$ ]] && (( focus_num >= 1 && focus_num <= num_tabs )); then
            break
        fi
        echo -e "${RED}  ✖ Enter a number between 1 and ${num_tabs}.${RESET}"
    done
    focus_idx=$(( focus_num - 1 ))
fi
focus_tab="${tab_names[$focus_idx]}"

# ── 4. Output script name ─────────────────────────────────────────────────────
echo ""
read -rp "$(echo -e "${YELLOW}Generated script name [kitty-tabs.sh]: ${RESET}")" out_name
[[ -z "$out_name" ]] && out_name="kitty-tabs.sh"
[[ "$out_name" != *.sh ]] && out_name="${out_name}.sh"
OUTPUT_SCRIPT="${SCRIPT_DIR}/${out_name}"

if [[ -f "$OUTPUT_SCRIPT" ]]; then
    echo -e "${YELLOW}  ⚠ ${OUTPUT_SCRIPT} already exists — it will be overwritten.${RESET}"
    read -rp "$(echo -e "${YELLOW}  Continue? [y/N]: ${RESET}")" overwrite
    [[ "${overwrite,,}" != "y" ]] && echo -e "${RED}Aborted.${RESET}" && exit 1
fi

# ── 5. Generate the tab script ────────────────────────────────────────────────
{
    printf '#!/usr/bin/env bash\n'
    printf '# Generated by pretabs-kitty.sh\n'
    printf '# Tabs : %s\n' "${tab_names[*]}"
    printf '# Focus: %s\n\n' "$focus_tab"

    printf "kitty @ set-tab-title '%s'\n" "${tab_names[0]}"

    for ((i = 1; i < num_tabs; i++)); do
        printf 'kitty @ launch --type=tab --tab-title "%s" --keep-focus\n' "${tab_names[$i]}"
    done

    if (( num_tabs > 1 )); then
        printf "kitty @ focus-tab --match 'title:%s'\n" "$focus_tab"
    fi
} > "$OUTPUT_SCRIPT"
chmod +x "$OUTPUT_SCRIPT"

echo ""
echo -e "${GREEN}  ✔ Script created:${RESET} ${BOLD}${OUTPUT_SCRIPT}${RESET}"

# ── 6. zshrc or manual ────────────────────────────────────────────────────────
echo ""
echo -e "${CYAN}What would you like to do next?${RESET}"
echo -e "  ${DIM}1)${RESET} Add it to ~/.zshrc — auto-launch on every new zsh session"
echo -e "  ${DIM}2)${RESET} Just show me the path — I'll run it myself"
while true; do
    read -rp "$(echo -e "${YELLOW}Choose [1/2]: ${RESET}")" choice
    [[ "$choice" == "1" || "$choice" == "2" ]] && break
    echo -e "${RED}  ✖ Enter 1 or 2.${RESET}"
done

if [[ "$choice" == "1" ]]; then
    ZSHRC="${HOME}/.zshrc"
    MARKER="# Pretabs-Kitty auto-launch"

    if grep -qF "$MARKER" "$ZSHRC" 2>/dev/null; then
        echo -e "${YELLOW}  ⚠ A Pretabs-Kitty entry already exists in ${ZSHRC} — skipping to avoid duplicates.${RESET}"
    else
        printf '\n%s\n' "$MARKER" >> "$ZSHRC"
        printf 'bash "%s"\n' "$OUTPUT_SCRIPT" >> "$ZSHRC"
        echo -e "${GREEN}  ✔ Added to ${ZSHRC}${RESET}"
        echo -e "${CYAN}  The tab layout will launch automatically on every new zsh session.${RESET}"
    fi
else
    echo ""
    echo -e "${GREEN}  Script is ready. Run it with:${RESET}"
    echo -e "  ${BOLD}bash ${OUTPUT_SCRIPT}${RESET}"
fi

echo ""
echo -e "${GREEN}  Done! Enjoy your Kitty tabs.${RESET}"
echo ""
